# Generated by Django 5.0.6 on 2024-05-16 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('sdate', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 17, 2, 33, 26, 974189))),
                ('edate', models.DateTimeField(verbose_name=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('starpoint', models.FloatField(default=5.0)),
            ],
        ),
    ]
