# Generated by Django 5.0.6 on 2024-05-18 15:11

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='author_email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='book',
            name='sell_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='edate',
            field=models.DateTimeField(verbose_name=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='book',
            name='sdate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 19, 0, 9, 24, 369263)),
        ),
    ]
